name: Eclecticlly workflow

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    name: set-up
    runs-on: ubuntu-latest
    steps:
      - name: set-up go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: install golint
        run: go install golang.org/x/lint/golint@latest
      - name: checkout repo
        uses: actions/checkout@v3
      - name: build application
        run: make
